### ISSUE TITLE
log4j 日志无法发送到 kafka

### ISSUE THREAD

**Issue by yeohx** [ameizi/kafka-log4j#1]
我的配置如下：
pom：
<dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>0.10.2.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.10</artifactId>
            <version>0.10.2.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-log4j-appender</artifactId>
            <version>0.10.2.1</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>18.0</version>
        </dependency>
    </dependencies>

log4j：

log4j.rootLogger=INFO,console
# for package com.demo.kafka, log would be sent to kafka appender.
log4j.logger=DEBUG,kafka
# appender kafka
log4j.appender.kafka=kafka.producer.KafkaLog4jAppender
log4j.appender.kafka.topic=test
# multiple brokers are separated by comma ",".
log4j.appender.kafka.brokerList=192.168.145.128:9092
log4j.appender.kafka.compressionType=none
log4j.appender.kafka.syncSend=true
log4j.appender.KAFKA.requiredNumAcks=0
log4j.appender.kafka.layout=org.apache.log4j.PatternLayout
log4j.appender.kafka.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L %% - %m%n
# appender console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.target=System.out
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d [%-5p] [%t] - [%l] %m%n

java代码：

import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import kafka.javaapi.producer.Producer;
import kafka.producer.KeyedMessage;
import kafka.producer.ProducerConfig;
import org.apache.log4j.Logger;

public class MyProducer {
    private static final Logger LOGGER = Logger.getLogger(MyProducer.class);
    private static final String TOPIC = "test";
    private static final String CONTENT = "This is a single message!!!";
    private static final String BROKER_LIST = "192.168.145.128:9092";
    private static final String SERIALIZER_CLASS = "kafka.serializer.StringEncoder";

    public static void main(String[] args) {
        LOGGER.error("start now!");
        Properties props = new Properties();
        props.put("serializer.class", SERIALIZER_CLASS);
        props.put("metadata.broker.list", BROKER_LIST);
        ProducerConfig config = new ProducerConfig(props);
        Producer<String, String> producer = new Producer<String, String>(config);
        //Send one message.
        KeyedMessage<String, String> message =
                new KeyedMessage<String, String>(TOPIC, CONTENT);
        producer.send(message);
        //Send multiple messages.
        List<KeyedMessage<String, String>> messages =
                new ArrayList<KeyedMessage<String, String>>();
        for (int i = 0; i < 5; i++) {
            messages.add(new KeyedMessage<String, String>
                    (TOPIC, "Multiple message at a time. " + i));
        }
        producer.send(messages);
    }
}

消息接收结果：
This is a single message!!!
Multiple message at a time. 0
Multiple message at a time. 1
Multiple message at a time. 2
Multiple message at a time. 3
Multiple message at a time. 4

根据上面的配置 producer 直接发送的消息。在kafka服务器上可以接收。LOGGER.error("start now!");日志消息在kafka上无法收到。
是否可以帮忙看一下问题原因

**Comment by github-liyan** [comment]
你的配置错误 删除log4j.logger=DEBUG,kafka 修改 log4j.rootLogger=INFO,console 为log4j.rootLogger=INFO,console,kafka
或者 修改 log4j.logger=DEBUG,kafka 为 log4j.logger.kafka=DEBUG,kafka 之后再修改 private static final Logger LOGGER = Logger.getLogger(MyProducer.class);为 private static final Logger LOGGER = Logger.getLogger("kafka");
建议按照第一种方式改
